### ISSUE TITLE
Current instructions for Travis-ci.org setup are either wrong or incomplete

### ISSUE THREAD

**Issue by revelt** [greenkeeperio/greenkeeper-lockfile#102]
hi all,

I try to enable `greenkeeper-lockfile` on Travis-ci.org, on an open source package, [string-remove-duplicate-heads-tails](https://github.com/codsen/string-remove-duplicate-heads-tails).

**I tried** the provided snippet for Travis,

```
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
```

![screen shot 2018-01-20 at 11 25 39](https://user-images.githubusercontent.com/8344688/35183383-0fd94b98-fddd-11e7-9cb6-dec5e948e56b.png)

**it does not work.** Each commit I publish consists of two commits actually, "master" and another that is incurred by `npm version ...`. I thought, maybe isolating "master"-only would help. Apparently, not. See the last line "except" I nicked from this package's `.travis.yml`:

```
language: node_js
node_js:
  - node
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
```

**I tried** specifying latest Node and targeting different Node versions, no luck.

I thought maybe I need to provide `GH_TOKEN` **explicitly** for this package. I generated the token, ran the Travis CLI `travis encrypt GH_TOKEN=<token> --add`, it added bunch of encrypted characters onto my `.travis.yml`, but that [didn't work either](https://travis-ci.org/codsen/string-remove-duplicate-heads-tails/jobs/331119995/config). Looks like it didn't recognise Node project and ran `rake`. Apparently, `language: node_js` row is obligatory...

I tried other variations of `.travis.yml` and none worked, often causing whole Travis build to [fail](https://travis-ci.org/codsen/string-remove-duplicate-heads-tails/builds/331126616).

---

**The documentation of this package is either incomplete or dare I say, also erroneous.** Besides Travis snippets in this documentation that don't work out-of-the-box, I want to make some observations:

> "First create a GitHub access token with push access to your repository and make it available to your CI's environment as GH_TOKEN."

1. does this apply to open source libraries ran from travis-ci.org?
2. do I have to generate a token for **each library separately** and add onto each libraries' `.travis.yml`?

> "Have a look at our Travis CI reference implementation."

Your implementation is not standard since _it is not using your supplied snippets_. Technically speaking, you're cheating - your `.travis.yml` links to JS files with a fancy custom setup. What we need is a link to _a normal open source library_ which uses `travis-ci.org` and which **used your setup instructions verbatim** and where Greenkeeper updated its lockfiles. 

Dear maintainers, I challenge you to find at least one open source library uses **your supplied Travis snippets** and link to it.

---

Personally, I find this tool impossible to set up. It took me all Saturday morning and within [8 attempts/tweaks/releases](https://travis-ci.org/codsen/string-remove-duplicate-heads-tails/builds) I could not get [string-remove-duplicate-heads-tails](https://github.com/codsen/string-remove-duplicate-heads-tails) Greenkeeper to update lockfiles. Greenkeeper itself, on other hand, activated automatically.

Dear maintainers, do you see my frustration here?

On the positive side, thank you for all this anyway; some tooling is better than no tooling and hopefully we can automate lockfile updates eventually. That would save lots of time maintaining OS libraries. 👍
