### ISSUE TITLE
How to make this work with `npm ci`?

### ISSUE THREAD

**Issue by Stupidism** [greenkeeperio/greenkeeper-lockfile#156]
I tried in travis and circleci:
```yml
install:
  - npm i -g npm@6
  - npm ci

# greenkeeper update npm lockfile
before_install:
  - npm install -g greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
after_success:
  - greenkeeper-lockfile-upload
  - bash <(curl -s https://codecov.io/bash)
```

```yml

      - run:
          name: Install greenkeeper-lockfile
          command: npm i greenkeeper-lockfile@1
      - run:
          name: Update lock file
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Install dependencies in ci mode
          command: npm ci
# Prevent to upload lockfile twice, because travis will upload, too.
#      - run:
#          name: Upload new lock file
#          command: ./node_modules/.bin/greenkeeper-lockfile-upload
```

But it always complains: 
```
This build should not update the lockfile. It could be a PR, not a branch build.
```

ci scripts: [travis](https://github.com/Stupidism/cra-rewired-starter/blob/greenkeeper/flow-bin-0.73.0/.travis.yml)
[circleci](https://github.com/Stupidism/cra-rewired-starter/blob/greenkeeper/flow-bin-0.73.0/.circleci/config.yml)

ci results:  [travis](https://travis-ci.org/Stupidism/cra-rewired-starter/builds/383518015)
[circleci](https://circleci.com/gh/Stupidism/cra-rewired-starter/370)
