### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by sudo-suhas** [greenkeeperio/greenkeeper-lockfile#44]
Can you please help me figure out what is going wrong?

PR - https://github.com/sudo-suhas/elastic-builder/pull/10
Travis build - https://travis-ci.org/sudo-suhas/elastic-builder/builds/247961511
Error message - `Error: Cannot find module 'resolve-from'`

<details>
<summary>Error stack trace</summary>

```
> elastic-builder@0.5.0 exec-tests /home/travis/build/sudo-suhas/elastic-builder
> cross-env NODE_ENV=test nyc --cache ava _build --concurrency 3
module.js:487
    throw err;
    ^
Error: Cannot find module 'resolve-from'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/sudo-suhas/elastic-builder/node_modules/import-local/node_modules/resolve-cwd/index.js:2:21)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/home/travis/build/sudo-suhas/elastic-builder/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/travis/build/sudo-suhas/elastic-builder/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/travis/build/sudo-suhas/elastic-builder/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
```

</details>
<br>

**Another instance**
PR - https://github.com/sudo-suhas/elastic-builder/pull/8
Travis Build - https://travis-ci.org/sudo-suhas/elastic-builder/builds/244604801
Error message - `Error: Cannot find module 'tapable'`

<details>
<summary>Error stack trace</summary>

```
> elastic-builder@0.5.0 precompile-tests /home/travis/build/sudo-suhas/elastic-builder
> cross-env NODE_ENV=test webpack --config webpack.config.test.js
module.js:487
    throw err;
    ^
Error: Cannot find module 'tapable'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/sudo-suhas/elastic-builder/node_modules/webpack/lib/Compiler.js:6:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

</details>
<br>
<details>
<summary>travis.yml</summary>

```yml
language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '7'
  - '6'
  - '4'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install:
# package-lock.json was introduced in npm@5
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: npm run check

# Only the node version 8 job will upload the lockfile
after_script:
  - greenkeeper-lockfile-upload
  - npm run coverage

```

</details>
